version: '3.8'
services:
  postgres:
    container_name: game_server_psql_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arturito
      POSTGRES_DB: gameserver
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 